
rsocket:
  brokers: tcp://localhost:9999
  jwt-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiIiwic2FzIjpbImQiLCJlIiwiZiIsImEiLCJ1IiwibCIsInQiXSwicm9sZXMiOlsiIl0sImlzcyI6IlJTb2NrZXRCcm9rZXIiLCJpZCI6IjVlN2RlNjZlLWQ4ODYtNDhkMi04YmRiLTk2MmQ2YTFjODc5MCIsIm9yZ3MiOlsiMiJdLCJpYXQiOjE2NjA1MjI4NDAsImF1dGhvcml0aWVzIjpbIiJdfQ.Yp5frypXmL82AXcrta1RYNauVZUhcObIORdRT4gBQHJuIsThqIy1ETBi27AIlZHTo9PlV6XZjPyfJWfmoutsI0KnY15PYj_HrK1JlU2KeHKnHObjCz2dyNUB1W2Dzzb8pOXelHdYRF4L69mOhtoC_Cc616w2tWakZs0AKiZTCaLdPbbreWIiR1cWVkykj2_8Cdlgh-rphgMbgLC6yalnSghDl_FUQb-8YS24Me61Di227JnjTnWUz5e0BtSF-9SuUS_qISPOoYUW_5koTbMs8cmko4q1s_AU3YVJVHAmixnF8O6r4zVZJotpnQyi-AOGX09r5oZSfUSnR9USSVsruA
  port: 2345
  metadata:
    owner: gateway
